# Generated by Django 2.1.5 on 2019-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender_identification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter the data which you want to analyse')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(help_text='Enter the data which you want to analyse'),
        ),
    ]
